version: "3.9"

services:
  redis:
    image: redis:alpine3.15
    container_name: redis

  db:
    image: postgres:14-alpine3.15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    container_name: postgres_db

  app:
    build:
      context: .
    command: >
      sh -c "
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000
      "    
    ports:
      - "8000:8000"
    image: app:django
    container_name: django-app-prod
    volumes:
      - app_data:/telegram-bot
    env_file: .env
    environment:
      - DEBUG=0
    depends_on:
      - db

  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l warning
    container_name: celery
    volumes:
      - app_data:/telegram-bot
    env_file: .env
    depends_on:
      - db
      - redis
      - app

volumes:
  postgres_data:
  app_data:

