version: "3.9"

services:
  redis:
    image: redis:alpine3.15
    container_name: redis

  db:
    image: postgres:14-alpine3.15
    volumes:
      - ./postgres-data/db:/var/lib/postgresql/data
    env_file: .env
    container_name: postgres_db

  app:
    build:
      context: .
    command: >
      sh -c "
             python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
            #  python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    image: app:django
    volumes:
      - .:/telegram-bot
    container_name: django-app
    env_file: .env
    depends_on:
      - db

  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l debug
    volumes:
      - .:/telegram-bot
    container_name: celery
    env_file: .env
    depends_on:
      - db
      - redis
      - app



