# Generated by Django 4.0.4 on 2022-04-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(choices=[('i', 'initial'), ('s', 'photo is sent')], default='i', max_length=64)),
            ],
        ),
    ]
