# Generated by Django 4.0.4 on 2022-04-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_bot', '0002_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(choices=[('1', 'Initial'), ('2', 'Photo is sent')], default='1', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
