# Generated by Django 4.0.4 on 2022-04-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_bot', '0005_subject_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstate',
            name='state',
            field=models.CharField(choices=[('1', 'Initial'), ('2', 'Photo is sent'), ('3', 'Creating new subject')], default='1', max_length=2),
        ),
    ]
