# Generated by Django 4.0.4 on 2022-04-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_bot', '0008_alter_image_media_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='media_group_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
