# Generated by Django 4.0.4 on 2022-04-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_bot', '0009_alter_image_media_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='first_in_media_group',
            field=models.BooleanField(default=False),
        ),
    ]
