# Generated by Django 4.0.4 on 2022-04-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_bot', '0010_image_first_in_media_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='first_in_media_group',
        ),
    ]
